In [1]:
import matplotlib.pyplot as plt
import os
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

### Prepare Carbon Dioxide Emissions Data

In [2]:
df_carbon = pd.read_csv(os.path.join('..', 'data', 'raw', 'carbon_dioxide_emissions.csv'), skiprows=4)

In [3]:
df_carbon.shape

(266, 71)

In [4]:
df_carbon.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0254,0.0290,0.0396,0.0445,0.0436,0.0576,0.0566,0.0673,0.0721,0.0761,0.0799,0.0831,0.0820,0.0846,0.0988,0.1043,0.1139,0.1289,0.1430,0.1976,0.2010,0.2264,0.2508,0.2516,0.2858,0.3144,0.2068,0.3430,0.3512,0.3559,0.2689,0.2719,0.2970,0.3424,0.3494,0.3853,0.4242,0.4581,0.4545,0.4933,0.4828,0.2907,0.3754,0.4128,0.4411,0.4625,0.4854,0.4671,0.4653,0.5095,0.4887,0.5074,0.5355,0.5371,0.5560,NaN,NaN
1,Africa Eastern and Southern,AFE,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,228.5328,227.1802,236.1448,257.7865,264.9263,277.4182,289.9791,293.7755,273.4407,279.7941,296.4287,308.1463,311.9771,315.0471,333.2586,341.1111,341.8973,362.7894,368.8669,366.0531,378.5089,370.7246,364.3912,364.4796,372.7987,392.5591,407.2145,423.8012,431.6088,418.7455,425.0290,436.8347,450.4351,473.9017,510.4845,524.9596,534.2167,557.2612,588.3964,561.8464,576.4621,569.3149,589.1126,613.4711,635.8143,623.6060,628.1540,637.9923,646.7127,655.3423,613.7192,631.4195,618.5414,619.3657,634.4063,NaN,NaN
2,Afghanistan,AFG,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.7328,1.7326,1.6924,1.7325,2.1886,2.0276,1.8913,2.2811,1.9327,2.0577,2.0047,2.2581,2.3078,2.9981,3.2205,4.1138,3.9312,3.2610,3.0734,2.8825,2.9084,2.8332,1.8107,1.7729,1.6737,1.4526,1.4056,1.3735,1.4093,1.3633,1.0093,0.9402,0.9388,1.0172,0.9024,1.2763,1.4185,2.0642,3.9029,6.1659,7.8684,11.5231,9.8844,8.4287,7.9588,8.4272,7.6117,10.3972,11.8099,12.1046,12.1436,12.4864,11.2980,11.6486,12.0684,NaN,NaN
3,Africa Western and Central,AFW,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.1109,57.2307,70.5594,91.7658,113.8977,91.2785,103.4932,90.4438,94.0519,124.1475,114.5027,98.8627,94.8713,96.6786,97.9266,102.0227,99.4147,96.0138,103.4746,108.6366,102.7861,108.0191,116.8794,115.0773,111.4841,121.6527,140.7737,140.1307,135.0323,136.9469,146.5159,155.4386,145.6422,158.0420,156.9244,158.2906,150.9714,146.1857,155.0185,147.3806,165.9665,176.9950,180.4170,197.3760,208.2070,209.7144,220.3771,216.0990,228.9951,239.1588,236.4906,255.7641,259.3996,251.6472,261.9340,NaN,NaN
4,Angola,AGO,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.9339,8.5196,10.3661,11.3470,11.8066,10.9045,7.2920,12.0335,14.2163,14.1795,14.3162,13.2323,12.7716,13.2214,13.3566,14.1038,14.2462,14.5017,14.9409,15.1036,11.2308,11.7805,12.1190,12.1418,11.4905,12.9537,15.6788,16.4022,17.0365,18.0315,16.5120,16.1923,15.9155,17.3297,17.6903,15.6389,16.3203,17.0559,19.1195,21.0889,22.7399,23.6501,24.7162,28.5343,30.8873,33.0865,31.2748,27.9951,25.8142,26.9963,20.5380,25.5641,26.6839,27.3360,28.1004,NaN,NaN

In [5]:
df_carbon.drop(columns=['Country Code', 'Indicator Code', '2025', 'Unnamed: 70'], inplace=True)

df_carbon = df_carbon.melt(
    id_vars=["Country Name", "Indicator Name"],
    var_name="Year",
    value_name="Value"
)

In [6]:
df_carbon.sample(10)

,Country Name,Indicator Name,Year,Value
7164,Ukraine,Carbon dioxide (CO2) emissions (total) excludi...,1986,686.4212
13898,Ecuador,Carbon dioxide (CO2) emissions (total) excludi...,2012,38.6610
16294,Euro area,Carbon dioxide (CO2) emissions (total) excludi...,2021,2147.1343
8083,IDA & IBRD total,Carbon dioxide (CO2) emissions (total) excludi...,1990,10258.6094
1785,Papua New Guinea,Carbon dioxide (CO2) emissions (total) excludi...,1966,NaN
6761,Ireland,Carbon dioxide (CO2) emissions (total) excludi...,1985,28.5910
14299,Romania,Carbon dioxide (CO2) emissions (total) excludi...,2013,79.5312
8457,El Salvador,Carbon dioxide (CO2) emissions (total) excludi...,1991,3.3093
12567,Europe & Central Asia,Carbon dioxide (CO2) emissions (total) excludi...,2007,7320.2365
12702,Qatar,Carbon dioxide (CO2) emissions (total) excludi...,2007,56.1475

---
### Prepare World Development Indicators Data

In [7]:
df_indicators = pd.read_csv(os.path.join('..', 'data', 'raw', 'world_development_indicators.csv'), skiprows=4)

In [8]:
df_indicators.shape

(13566, 71)

In [9]:
df_indicators.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Urban population (% of total population),SP.URB.TOTL.IN.ZS,59.02367,59.072800,59.212271,59.432359,59.723340,60.075491,60.479087,60.924404,61.401720,61.901310,62.413451,62.928418,63.436488,63.927938,64.393043,64.822080,65.205326,65.533055,65.795545,65.983072,66.085912,66.099117,66.070619,66.014907,65.939353,65.850448,65.754682,65.658546,65.568529,65.491123,65.432816,65.400922,65.390589,65.384467,65.380048,65.376703,65.373804,65.370721,65.366825,65.361486,65.354550,65.335114,65.282069,65.198292,65.088653,64.958023,64.811270,64.653266,64.488881,64.322985,64.161297,63.999261,63.825209,63.638291,63.439253,63.228837,63.007788,62.776849,62.536764,62.288276,62.002884,61.927534,61.881166,61.835149,61.790940,NaN,NaN
1,Aruba,ABW,Urban population,SP.URB.TOTL,32417.00000,32831.000000,33348.000000,33878.000000,34412.000000,34958.000000,35498.000000,35939.000000,36269.000000,36554.000000,36793.000000,36990.000000,36823.000000,37269.000000,37573.000000,37788.000000,38059.000000,38389.000000,38672.000000,39056.000000,39591.000000,40032.000000,40485.000000,41080.000000,41477.000000,40648.000000,39407.000000,38843.000000,38902.000000,39585.000000,41061.000000,43097.000000,45123.000000,48179.000000,50732.000000,52174.000000,54274.000000,56416.000000,57818.000000,58602.000000,59203.000000,59742.000000,60108.000000,60718.000000,61924.000000,63422.000000,64426.000000,64750.000000,65080.000000,65355.000000,65341.000000,65657.000000,66448.000000,67250.000000,67758.000000,68228.000000,68506.000000,68260.000000,68108.000000,68021.000000,67327.000000,66696.000000,66405.000000,66386.000000,66731.000000,NaN,NaN
2,Aruba,ABW,Urban population growth (annual %),SP.URB.GROW,NaN,1.269021,1.562461,1.576804,1.563950,1.574200,1.532902,1.234670,0.914033,0.782724,0.651699,0.534000,-0.452496,1.203923,0.812383,0.570588,0.714600,0.863337,0.734486,0.988069,1.360531,1.107731,1.125240,1.458985,0.961767,-2.018942,-3.100617,-1.441559,0.151778,1.740460,3.660851,4.839462,4.593871,6.553115,5.163363,2.802741,3.946100,3.870752,2.454734,1.346868,1.020339,0.906307,0.610765,1.009725,1.966763,2.390298,1.570647,0.501642,0.508358,0.421667,-0.021424,0.482451,1.197547,1.199733,0.752552,0.691250,0.406629,-0.359739,-0.222926,-0.127820,-1.025514,-0.941636,-0.437263,-0.028616,0.518342,NaN,NaN
3,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.00000,55578.000000,56320.000000,57002.000000,57619.000000,58190.000000,58694.000000,58990.000000,59069.000000,59052.000000,58950.000000,58781.000000,58047.000000,58299.000000,58349.000000,58295.000000,58368.000000,58580.000000,58776.000000,59191.000000,59909.000000,60563.000000,61276.000000,62228.000000,62901.000000,61728.000000,59931.000000,59159.000000,59331.000000,60443.000000,62753.000000,65896.000000,69005.000000,73685.000000,77595.000000,79805.000000,83021.000000,86301.000000,88451.000000,89659.000000,90588.000000,91439.000000,92074.000000,93128.000000,95138.000000,97635.000000,99405.000000,100150.000000,100917.000000,101604.000000,101838.000000,102591.000000,104110.000000,105675.000000,106807.000000,107906.000000,108727.000000,108735.000000,108908.000000,109203.000000,108587.000000,107700.000000,107310.000000,107359.000000,107995.000000,NaN,NaN
4,Aruba,ABW,Population growth (annual %),SP.POP.GROW,NaN,1.187344,1.326227,1.203664,1.076602,0.986114,0.862399,0.503043,0.133831,-0.028784,-0.172878,-0.287095,-1.256565,0.433191,0.085728,-0.092589,0.125147,0.362555,0.334027,0.703589,1.205724,1.085740,1.170410,1.541681,1.075700,-1.882443,-2.954374,-1.296517,0.290320,1.856884,3.750561,4.887136,4.610122,6.562028,5.170374,2.808317,3.950743,3.874760,2.460754,1.356486,1.030817,0.935033,0.692052,1.138229,2.135358,2.590757,1.796638,0.746665,0.762933,0.678451,0.230041,0.736689,1.469782,1.492031,1.065512,1.023701,0.757968,0.007358,0.158976,0.270505,-0.565684,-0.820211,-0.362774,0.045652,0.590657,NaN,NaN

In [10]:
df_indicators.drop(columns=['Country Code', 'Indicator Code', '2025', 'Unnamed: 70'], inplace=True)

df_indicators = df_indicators.melt(
    id_vars=["Country Name", "Indicator Name"],
    var_name="Year",
    value_name="Value"
)

In [11]:
df_indicators.sample(20)

,Country Name,Indicator Name,Year,Value
363155,South Asia,Electricity production from coal sources (% of...,1986,NaN
490232,Central Europe and the Baltics,Urban population living in areas where elevati...,1996,NaN
428050,St. Martin (French part),"Community health workers (per 1,000 people)",1991,NaN
372400,Japan,Agricultural land (% of land area),1987,16.341196
165187,Comoros,Agricultural land (% of land area),1972,51.047824
142889,Lesotho,Cereal yield (kg per hectare),1970,605.500000
383542,Ethiopia,"Droughts, floods, extreme temperatures (% of p...",1988,NaN
57728,"Egypt, Arab Rep.",Rural land area where elevation is below 5 met...,1964,NaN
548349,Ireland,Arable land (% of land area),2000,7.085208
541029,Tajikistan,Rural population living in areas where elevati...,1999,NaN
369845,Eritrea,Urban land area where elevation is below 5 met...,1987,NaN
119080,Sudan,Rural land area where elevation is below 5 met...,1968,NaN
56580,Colombia,Rural population living in areas where elevati...,1964,NaN
226805,Pre-demographic dividend,"Mortality rate, under-5 (per 1,000 live births)",1976,NaN
284781,South Africa,Arable land (% of land area),1980,10.168248
135621,Zimbabwe,CPIA public sector management and institutions...,1969,NaN
662240,Sub-Saharan Africa,Poverty headcount ratio at $3.00 a day (2021 P...,2008,51.600000
166007,East Asia & Pacific,Urban population growth (annual %),1972,2.679334
28567,Bolivia,"Community health workers (per 1,000 people)",1962,NaN
574948,Hungary,Electric power consumption (kWh per capita),2002,3545.170756

---
### Merge Data

In [12]:
df_merged = pd.concat([df_carbon, df_indicators])

In [13]:
df_merged.sample(20)

,Country Name,Indicator Name,Year,Value
163263,Argentina,CPIA public sector management and institutions...,1972,NaN
80753,St. Vincent and the Grenadines,Urban population living in areas where elevati...,1965,NaN
73027,Hungary,Rural land area where elevation is below 5 met...,1965,NaN
115500,Low income,Access to electricity (% of population),1968,NaN
729183,French Polynesia,Access to electricity (% of population),2013,1.000000e+02
87210,Iceland,Urban population (% of total population),1966,8.353867e+01
367786,Brazil,Electric power consumption (kWh per capita),1987,NaN
667864,East Asia & Pacific (excluding high income),Population living in areas where elevation is ...,2009,NaN
732083,Virgin Islands (U.S.),"Electricity production from renewable sources,...",2013,1.520000e+06
317115,Croatia,Arable land (% of land area),1983,NaN
727297,Montenegro,"Foreign direct investment, net inflows (% of GDP)",2013,1.009605e+01
366475,Africa Western and Central,Agricultural irrigated land (% of total agricu...,1987,NaN
207943,Guinea-Bissau,"Annual freshwater withdrawals, total (% of int...",1975,NaN
247104,Dominica,"Primary completion rate, total (% of relevant ...",1978,NaN
266766,Netherlands,Access to electricity (% of population),1979,NaN
252855,Malaysia,Arable land (% of land area),1978,3.271953e+00
546830,Georgia,"Mortality rate, under-5 (per 1,000 live births)",2000,3.630000e+01
319611,Morocco,Urban land area where elevation is below 5 met...,1983,NaN
320261,"Middle East, North Africa, Afghanistan & Pakis...",Electricity production from nuclear sources (%...,1983,NaN
187234,"Somalia, Fed. Rep.",Terrestrial and marine protected areas (% of t...,1973,NaN

In [14]:
df_merged["Year"] = df_merged["Year"].astype(int)
df_merged["Value"] = pd.to_numeric(df_merged["Value"], errors="coerce")

In [15]:
df_merged.sample(20)

,Country Name,Indicator Name,Year,Value
512829,"Somalia, Fed. Rep.",Energy use (kg of oil equivalent per capita),1997,NaN
12939,St. Vincent and the Grenadines,Access to electricity (% of population),1960,NaN
142476,St. Lucia,Electricity production from natural gas source...,1970,NaN
393589,Africa Western and Central,"Droughts, floods, extreme temperatures (% of p...",1989,NaN
147242,Syrian Arab Republic,Poverty headcount ratio at $3.00 a day (2021 P...,1970,NaN
134480,Trinidad and Tobago,Urban land area where elevation is below 5 met...,1969,NaN
39230,Timor-Leste,"Agriculture, forestry, and fishing, value adde...",1962,NaN
457129,Panama,"Annual freshwater withdrawals, total (% of int...",1993,NaN
344613,IDA only,"Prevalence of underweight, weight for age (% o...",1985,NaN
611118,Antigua and Barbuda,Access to electricity (% of population),2005,92.200000
203564,Africa Eastern and Southern,Disaster risk reduction progress score (1-5 sc...,1975,NaN
260563,Germany,Population growth (annual %),1979,0.044207
446461,Trinidad and Tobago,"Community health workers (per 1,000 people)",1992,NaN
347406,"Middle East, North Africa, Afghanistan & Pakis...",Urban land area where elevation is below 5 met...,1985,NaN
151348,Cote d'Ivoire,Electricity production from oil sources (% of ...,1971,NaN
789436,Curacao,"Community health workers (per 1,000 people)",2018,NaN
143992,Mongolia,Population living in areas where elevation is ...,1970,NaN
441671,Morocco,"Agriculture, forestry, and fishing, value adde...",1992,14.042757
288824,France,"Agriculture, forestry, and fishing, value adde...",1981,3.339267
753309,Low & middle income,Average precipitation in depth (mm per year),2015,NaN

In [16]:
df_final = df_merged.pivot_table(
    index=["Country Name", "Year"],
    columns="Indicator Name",
    values="Value"
).reset_index()

In [17]:
df_final.head(10)

Indicator Name,Country Name,Year,Access to electricity (% of population),Agricultural irrigated land (% of total agricultural land),Agricultural land (% of land area),Agricultural land (sq. km),"Agriculture, forestry, and fishing, value added (% of GDP)","Annual freshwater withdrawals, total (% of internal resources)","Annual freshwater withdrawals, total (billion cubic meters)",Arable land (% of land area),Average precipitation in depth (mm per year),CPIA public sector management and institutions cluster average (1=low to 6=high),Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e),Cereal yield (kg per hectare),"Community health workers (per 1,000 people)",Disaster risk reduction progress score (1-5 scale; 5=best),"Droughts, floods, extreme temperatures (% of population, average 1990-2009)",Electric power consumption (kWh per capita),Electricity production from coal sources (% of total),Electricity production from hydroelectric sources (% of total),Electricity production from natural gas sources (% of total),Electricity production from nuclear sources (% of total),Electricity production from oil sources (% of total),"Electricity production from renewable sources, excluding hydroelectric (% of total)","Electricity production from renewable sources, excluding hydroelectric (kWh)",Energy use (kg of oil equivalent per capita),"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2021 PPP)","Foreign direct investment, net inflows (% of GDP)",Forest area (% of land area),Forest area (sq. km),Land area where elevation is below 5 meters (% of total land area),Marine protected areas (% of territorial waters),"Mortality rate, under-5 (per 1,000 live births)",Population growth (annual %),Population in urban agglomerations of more than 1 million (% of total population),Population living in areas where elevation is below 5 meters (% of total population),"Population, total",Poverty headcount ratio at $3.00 a day (2021 PPP) (% of population),"Prevalence of underweight, weight for age (% of children under 5)","Primary completion rate, total (% of relevant age group)",Renewable electricity output (% of total electricity output),Renewable energy consumption (% of total final energy consumption),Rural land area where elevation is below 5 meters (% of total land area),Rural land area where elevation is below 5 meters (sq. km),Rural population living in areas where elevation is below 5 meters (% of total population),"School enrollment, primary and secondary (gross), gender parity index (GPI)",Terrestrial and marine protected areas (% of total territorial area),Terrestrial protected areas (% of total land area),Urban land area where elevation is below 5 meters (% of total land area),Urban land area where elevation is below 5 meters (sq. km),Urban population,Urban population (% of total population),Urban population growth (annual %),Urban population living in areas where elevation is below 5 meters (% of total population)
0,Afghanistan,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,353.2,NaN,3.158280,NaN,9035043.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,733876.0,8.122551,NaN,NaN
1,Afghanistan,1961,NaN,NaN,57.878356,377500.0,NaN,NaN,NaN,11.728991,327.0,NaN,NaN,1115.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347.6,1.962239,3.259782,NaN,9214083.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,773024.0,8.389595,5.197002,NaN
2,Afghanistan,1962,NaN,NaN,57.955016,378000.0,NaN,NaN,NaN,11.805651,327.0,NaN,NaN,1079.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,342.3,2.044523,3.362009,NaN,9404406.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,814672.0,8.662664,5.247548,NaN
3,Afghanistan,1963,NaN,NaN,58.031676,378500.0,NaN,NaN,NaN,11.882311,327.0,NaN,NaN,985.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336.8,2.105208,3.465349,NaN,9604487.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,858901.0,8.942709,5.286809,NaN
4,Afghanistan,1964,NaN,NaN,58.116002,379050.0,NaN,NaN,NaN,11.958972,327.0,NaN,NaN,1082.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,331.7,2.161195,3.570111,NaN,9814318.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,905973.0,9.231134,5.335584,NaN
5,Afghanistan,1965,NaN,NaN,58.123668,379100.0,NaN,NaN,NaN,11.958972,327.0,NaN,NaN,1098.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,326.5,2.233709,3.674858,NaN,10036008.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,956366.0,9.529343,5.413118,NaN
6,Afghanistan,1966,NaN,NaN,58.192662,379550.0,NaN,NaN,NaN,12.012634,327.0,NaN,NaN,1012.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,321.5,2.269651,3.781581,NaN,10266395.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1010084.0,9.838740,5.464809,NaN
7,Afghanistan,1967,NaN,NaN,58.229459,379790.0,NaN,NaN,NaN,12.026432,327.0,NaN,NaN,1224.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,316.6,2.306668,3.884338,NaN,10505959.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1067482.0,10.160728,5.526911,NaN
8,Afghanistan,1968,NaN,NaN,58.230992,379800.0,NaN,NaN,NaN,12.026432,327.0,NaN,NaN,1287.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.6,2.360683,3.982208,NaN,10756922.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1129123.0,10.496712,5.613862,NaN
9,Afghanistan,1969,NaN,NaN,58.255523,379960.0,NaN,NaN,NaN,12.050964,327.0,NaN,NaN,1310.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,306.4,2.392720,4.080678,NaN,11017409.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1195179.0,10.848095,5.685474,NaN

---
### Split Data

In [18]:
cutoff_year_test = 2021

In [19]:
train_df = df_final[df_final['Year'] < cutoff_year_test]
test_df = df_final[cutoff_year_test <= df_final['Year']]

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Train shape: (16165, 54)
Test shape: (1060, 54)

In [20]:
train_df.head()

Indicator Name,Country Name,Year,Access to electricity (% of population),Agricultural irrigated land (% of total agricultural land),Agricultural land (% of land area),Agricultural land (sq. km),"Agriculture, forestry, and fishing, value added (% of GDP)","Annual freshwater withdrawals, total (% of internal resources)","Annual freshwater withdrawals, total (billion cubic meters)",Arable land (% of land area),Average precipitation in depth (mm per year),CPIA public sector management and institutions cluster average (1=low to 6=high),Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e),Cereal yield (kg per hectare),"Community health workers (per 1,000 people)",Disaster risk reduction progress score (1-5 scale; 5=best),"Droughts, floods, extreme temperatures (% of population, average 1990-2009)",Electric power consumption (kWh per capita),Electricity production from coal sources (% of total),Electricity production from hydroelectric sources (% of total),Electricity production from natural gas sources (% of total),Electricity production from nuclear sources (% of total),Electricity production from oil sources (% of total),"Electricity production from renewable sources, excluding hydroelectric (% of total)","Electricity production from renewable sources, excluding hydroelectric (kWh)",Energy use (kg of oil equivalent per capita),"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2021 PPP)","Foreign direct investment, net inflows (% of GDP)",Forest area (% of land area),Forest area (sq. km),Land area where elevation is below 5 meters (% of total land area),Marine protected areas (% of territorial waters),"Mortality rate, under-5 (per 1,000 live births)",Population growth (annual %),Population in urban agglomerations of more than 1 million (% of total population),Population living in areas where elevation is below 5 meters (% of total population),"Population, total",Poverty headcount ratio at $3.00 a day (2021 PPP) (% of population),"Prevalence of underweight, weight for age (% of children under 5)","Primary completion rate, total (% of relevant age group)",Renewable electricity output (% of total electricity output),Renewable energy consumption (% of total final energy consumption),Rural land area where elevation is below 5 meters (% of total land area),Rural land area where elevation is below 5 meters (sq. km),Rural population living in areas where elevation is below 5 meters (% of total population),"School enrollment, primary and secondary (gross), gender parity index (GPI)",Terrestrial and marine protected areas (% of total territorial area),Terrestrial protected areas (% of total land area),Urban land area where elevation is below 5 meters (% of total land area),Urban land area where elevation is below 5 meters (sq. km),Urban population,Urban population (% of total population),Urban population growth (annual %),Urban population living in areas where elevation is below 5 meters (% of total population)
0,Afghanistan,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,353.2,NaN,3.158280,NaN,9035043.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,733876.0,8.122551,NaN,NaN
1,Afghanistan,1961,NaN,NaN,57.878356,377500.0,NaN,NaN,NaN,11.728991,327.0,NaN,NaN,1115.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347.6,1.962239,3.259782,NaN,9214083.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,773024.0,8.389595,5.197002,NaN
2,Afghanistan,1962,NaN,NaN,57.955016,378000.0,NaN,NaN,NaN,11.805651,327.0,NaN,NaN,1079.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,342.3,2.044523,3.362009,NaN,9404406.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,814672.0,8.662664,5.247548,NaN
3,Afghanistan,1963,NaN,NaN,58.031676,378500.0,NaN,NaN,NaN,11.882311,327.0,NaN,NaN,985.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336.8,2.105208,3.465349,NaN,9604487.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,858901.0,8.942709,5.286809,NaN
4,Afghanistan,1964,NaN,NaN,58.116002,379050.0,NaN,NaN,NaN,11.958972,327.0,NaN,NaN,1082.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,331.7,2.161195,3.570111,NaN,9814318.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,905973.0,9.231134,5.335584,NaN

In [21]:
test_df.head()

Indicator Name,Country Name,Year,Access to electricity (% of population),Agricultural irrigated land (% of total agricultural land),Agricultural land (% of land area),Agricultural land (sq. km),"Agriculture, forestry, and fishing, value added (% of GDP)","Annual freshwater withdrawals, total (% of internal resources)","Annual freshwater withdrawals, total (billion cubic meters)",Arable land (% of land area),Average precipitation in depth (mm per year),CPIA public sector management and institutions cluster average (1=low to 6=high),Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e),Cereal yield (kg per hectare),"Community health workers (per 1,000 people)",Disaster risk reduction progress score (1-5 scale; 5=best),"Droughts, floods, extreme temperatures (% of population, average 1990-2009)",Electric power consumption (kWh per capita),Electricity production from coal sources (% of total),Electricity production from hydroelectric sources (% of total),Electricity production from natural gas sources (% of total),Electricity production from nuclear sources (% of total),Electricity production from oil sources (% of total),"Electricity production from renewable sources, excluding hydroelectric (% of total)","Electricity production from renewable sources, excluding hydroelectric (kWh)",Energy use (kg of oil equivalent per capita),"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2021 PPP)","Foreign direct investment, net inflows (% of GDP)",Forest area (% of land area),Forest area (sq. km),Land area where elevation is below 5 meters (% of total land area),Marine protected areas (% of territorial waters),"Mortality rate, under-5 (per 1,000 live births)",Population growth (annual %),Population in urban agglomerations of more than 1 million (% of total population),Population living in areas where elevation is below 5 meters (% of total population),"Population, total",Poverty headcount ratio at $3.00 a day (2021 PPP) (% of population),"Prevalence of underweight, weight for age (% of children under 5)","Primary completion rate, total (% of relevant age group)",Renewable electricity output (% of total electricity output),Renewable energy consumption (% of total final energy consumption),Rural land area where elevation is below 5 meters (% of total land area),Rural land area where elevation is below 5 meters (sq. km),Rural population living in areas where elevation is below 5 meters (% of total population),"School enrollment, primary and secondary (gross), gender parity index (GPI)",Terrestrial and marine protected areas (% of total territorial area),Terrestrial protected areas (% of total land area),Urban land area where elevation is below 5 meters (% of total land area),Urban land area where elevation is below 5 meters (sq. km),Urban population,Urban population (% of total population),Urban population growth (annual %),Urban population living in areas where elevation is below 5 meters (% of total population)
61,Afghanistan,2021,97.700000,6.321614,58.741548,383130.000,33.597619,43.015907,20.282000,12.003434,327.0,NaN,12.4864,2099.100000,NaN,NaN,NaN,NaN,0.000000,71.656183,0.000000,0.000000,21.765525,6.578292,7.791000e+07,NaN,NaN,0.144467,1.852782,12084.400,NaN,NaN,59.300000,2.356098,10.839313,NaN,40000412.0,NaN,NaN,NaN,78.234475,20.0,NaN,NaN,NaN,NaN,3.600000,3.600000,NaN,NaN,10139249.0,25.347862,2.694569,NaN
62,Afghanistan,2022,85.300000,5.828309,58.741548,383130.000,33.701432,43.015907,20.282000,11.974304,327.0,1.700000,11.2980,2193.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.852782,12084.400,NaN,NaN,57.400000,1.435704,10.985730,NaN,40578842.0,NaN,18.4,NaN,NaN,20.0,NaN,NaN,NaN,NaN,3.600000,3.600000,NaN,NaN,10304561.0,25.393925,1.617268,NaN
63,Afghanistan,2023,85.300000,5.979116,58.439508,381160.000,34.743247,NaN,NaN,12.029499,NaN,1.600000,11.6486,2295.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.852782,12084.400,NaN,NaN,55.500000,2.135594,11.069093,NaN,41454761.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,3.600000,NaN,NaN,10559793.0,25.473053,2.446706,NaN
64,Afghanistan,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,12.0684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.836573,11.087133,NaN,42647492.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,3.600000,NaN,NaN,10960719.0,25.700735,3.726421,NaN
126,Africa Eastern and Southern,2021,48.127211,NaN,46.510566,6904535.522,13.728741,5.041739,100.105995,8.325633,NaN,2.736842,631.4195,1923.422312,NaN,NaN,NaN,514.341833,54.663797,28.186480,2.615079,3.139947,4.734768,4.939318,1.943513e+10,579.816693,137.635964,4.924360,29.955194,4446875.546,NaN,8.502964,57.140506,2.649439,14.508221,NaN,713090928.0,NaN,NaN,71.790733,33.125799,NaN,NaN,NaN,NaN,NaN,13.767189,16.740378,NaN,NaN,263191471.0,36.908543,3.794516,NaN

In [22]:
train_df.to_csv(os.path.join('..', 'data', 'raw', 'train.csv'), index=False)
test_df.to_csv(os.path.join('..', 'data', 'raw', 'test.csv'), index=False)