In [16]:
import matplotlib.pyplot as plt
import os
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [29]:
df = pd.read_csv(os.path.join('..', 'data', 'raw', 'carbon_dioxide_emissions.csv'), skiprows=4)

In [23]:
df.shape

(266, 71)

In [24]:
df.head(2)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0254,0.0290,0.0396,0.0445,0.0436,0.0576,0.0566,0.0673,0.0721,0.0761,0.0799,0.0831,0.0820,0.0846,0.0988,0.1043,0.1139,0.1289,0.1430,0.1976,0.2010,0.2264,0.2508,0.2516,0.2858,0.3144,0.2068,0.3430,0.3512,0.3559,0.2689,0.2719,0.2970,0.3424,0.3494,0.3853,0.4242,0.4581,0.4545,0.4933,0.4828,0.2907,0.3754,0.4128,0.4411,0.4625,0.4854,0.4671,0.4653,0.5095,0.4887,0.5074,0.5355,0.5371,0.5560,NaN,NaN
1,Africa Eastern and Southern,AFE,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,228.5328,227.1802,236.1448,257.7865,264.9263,277.4182,289.9791,293.7755,273.4407,279.7941,296.4287,308.1463,311.9771,315.0471,333.2586,341.1111,341.8973,362.7894,368.8669,366.0531,378.5089,370.7246,364.3912,364.4796,372.7987,392.5591,407.2145,423.8012,431.6088,418.7455,425.0290,436.8347,450.4351,473.9017,510.4845,524.9596,534.2167,557.2612,588.3964,561.8464,576.4621,569.3149,589.1126,613.4711,635.8143,623.6060,628.1540,637.9923,646.7127,655.3423,613.7192,631.4195,618.5414,619.3657,634.4063,NaN,NaN

In [25]:
year_cols = [c for c in df.columns if c.isdigit()]
df[year_cols].notna().sum()

1960      0
1961      0
1962      0
1963      0
1964      0
1965      0
1966      0
1967      0
1968      0
1969      0
1970    251
1971    251
1972    251
1973    251
1974    251
1975    251
1976    251
1977    251
1978    251
1979    251
1980    251
1981    251
1982    251
1983    251
1984    251
1985    251
1986    251
1987    251
1988    251
1989    251
1990    251
1991    251
1992    251
1993    251
1994    251
1995    251
1996    251
1997    251
1998    251
1999    251
2000    251
2001    251
2002    251
2003    251
2004    251
2005    251
2006    251
2007    251
2008    251
2009    251
2010    251
2011    251
2012    251
2013    251
2014    251
2015    251
2016    251
2017    251
2018    251
2019    251
2020    251
2021    251
2022    251
2023    251
2024    251
2025      0
dtype: int64

In [30]:
df.drop(columns=['Indicator Name', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '2025', 'Unnamed: 70'], inplace=True)

In [37]:
# Train set: 

# identify year columns
year_cols = [c for c in df.columns if c.isdigit()]

# long format
long_df = df.melt(
    id_vars=['Country Name', 'Country Code', 'Indicator Code'],
    value_vars=year_cols,
    var_name='Year',
    value_name='CO2_Mt'
)

long_df['Year'] = long_df['Year'].astype(int)

# pivot to years as rows, countries as columns
wide_year_country = long_df.pivot_table(
    index='Year',
    columns=['Country Name', 'Country Code', 'Indicator Code'],
    values='CO2_Mt'
)

wide_year_country.head()

Country Name,Afghanistan,Africa Eastern and Southern,Africa Western and Central,Albania,Algeria,American Samoa,Angola,Antigua and Barbuda,Arab World,Argentina,Armenia,Aruba,Australia,Austria,Azerbaijan,"Bahamas, The",Bahrain,Bangladesh,Barbados,Belarus,Belgium,Belize,Benin,Bermuda,Bhutan,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,British Virgin Islands,Brunei Darussalam,Bulgaria,Burkina Faso,Burundi,Cabo Verde,Cambodia,Cameroon,Canada,Caribbean small states,Cayman Islands,Central African Republic,Central Europe and the Baltics,Chad,Chile,China,Colombia,Comoros,"Congo, Dem. Rep.","Congo, Rep.",Costa Rica,Cote d'Ivoire,Croatia,Cuba,Cyprus,Czechia,Denmark,Djibouti,Dominica,Dominican Republic,Early-demographic dividend,East Asia & Pacific,East Asia & Pacific (IDA & IBRD countries),East Asia & Pacific (excluding high income),Ecuador,"Egypt, Arab Rep.",El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia,Euro area,Europe & Central Asia,Europe & Central Asia (IDA & IBRD countries),Europe & Central Asia (excluding high income),European Union,Faroe Islands,Fiji,Finland,Fragile and conflict affected situations,France,French Polynesia,Gabon,"Gambia, The",Georgia,Germany,Ghana,Gibraltar,Greece,Greenland,Grenada,Guam,Guatemala,Guinea,Guinea-Bissau,Guyana,Haiti,Heavily indebted poor countries (HIPC),High income,Honduras,"Hong Kong SAR, China",Hungary,IBRD only,IDA & IBRD total,IDA blend,IDA only,IDA total,Iceland,India,Indonesia,"Iran, Islamic Rep.",Iraq,Ireland,Israel,Italy,Jamaica,Japan,Jordan,Kazakhstan,Kenya,Kiribati,"Korea, Dem. People's Rep.","Korea, Rep.",Kuwait,Kyrgyz Republic,Lao PDR,Late-demographic dividend,Latin America & Caribbean,Latin America & Caribbean (excluding high income),Latin America & the Caribbean (IDA & IBRD countries),Latvia,Least developed countries: UN classification,Lebanon,Lesotho,Liberia,Libya,Lithuania,Low & middle income,Low income,Lower middle income,Luxembourg,"Macao SAR, China",Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Mauritania,Mauritius,Mexico,"Micronesia, Fed. Sts.","Middle East, North Africa, Afghanistan & Pakistan","Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)","Middle East, North Africa, Afghanistan & Pakistan (excluding high income)",Middle income,Moldova,Mongolia,Morocco,Mozambique,Myanmar,Namibia,Nauru,Nepal,Netherlands,New Caledonia,New Zealand,Nicaragua,Niger,Nigeria,North America,North Macedonia,Northern Mariana Islands,Norway,OECD members,Oman,Other small states,Pacific island small states,Pakistan,Palau,Panama,Papua New Guinea,Paraguay,Peru,Philippines,Poland,Portugal,Post-demographic dividend,Pre-demographic dividend,Puerto Rico (US),Qatar,Romania,Russian Federation,Rwanda,Samoa,Sao Tome and Principe,Saudi Arabia,Senegal,Seychelles,Sierra Leone,Singapore,Slovak Republic,Slovenia,Small states,Solomon Islands,"Somalia, Fed. Rep.",South Africa,South Asia,South Asia (IDA & IBRD),Spain,Sri Lanka,St. Kitts and Nevis,St. Lucia,St. Vincent and the Grenadines,Sub-Saharan Africa,Sub-Saharan Africa (IDA & IBRD countries),Sub-Saharan Africa (excluding high income),Sudan,Suriname,Sweden,Switzerland,Syrian Arab Republic,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Tonga,Trinidad and Tobago,Tunisia,Turkiye,Turkmenistan,Turks and Caicos Islands,Tuvalu,Uganda,Ukraine,United Arab Emirates,United Kingdom,United States,Upper middle income,Uruguay,Uzbekistan,Vanuatu,"Venezuela, RB",Viet Nam,Virgin Islands (U.S.),World,"Yemen, Rep.",Zambia,Zimbabwe
Country Code,AFG,AFE,AFW,ALB,DZA,ASM,AGO,ATG,ARB,ARG,ARM,ABW,AUS,AUT,AZE,BHS,BHR,BGD,BRB,BLR,BEL,BLZ,BEN,BMU,BTN,BOL,BIH,BWA,BRA,VGB,BRN,BGR,BFA,BDI,CPV,KHM,CMR,CAN,CSS,CYM,CAF,CEB,TCD,CHL,CHN,COL,COM,COD,COG,CRI,CIV,HRV,CUB,CYP,CZE,DNK,DJI,DMA,DOM,EAR,EAS,TEA,EAP,ECU,EGY,SLV,GNQ,ERI,EST,SWZ,ETH,EMU,ECS,TEC,ECA,EUU,FRO,FJI,FIN,FCS,FRA,PYF,GAB,GMB,GEO,DEU,GHA,GIB,GRC,GRL,GRD,GUM,GTM,GIN,GNB,GUY,HTI,HPC,HIC,HND,HKG,HUN,IBD,IBT,IDB,IDX,IDA,ISL,IND,IDN,IRN,IRQ,IRL,ISR,ITA,JAM,JPN,JOR,KAZ,KEN,KIR,PRK,KOR,KWT,KGZ,LAO,LTE,LCN,LAC,TLA,LVA,LDC,LBN,LSO,LBR,LBY,LTU,LMY,LIC,LMC,LUX,MAC,MDG,MWI,MYS,MDV,MLI,MLT,MHL,MRT,MUS,MEX,FSM,MEA,TMN,MNA,MIC,MDA,MNG,MAR,MOZ,MMR,NAM,NRU,NPL,NLD,NCL,NZL,NIC,NER,NGA,NAC,MKD,MNP,NOR,OED,OMN,OSS,PSS,PAK,PLW,PAN,PNG,PRY,PER,PHL,POL,PRT,PST,PRE,PRI,QAT,ROU,RUS,RWA,WSM,STP,SAU,SEN,SYC,SLE,SGP,SVK,SVN,SST,SLB,SOM,ZAF,SAS,TSA,ESP,LKA,KNA,LCA,VCT,SSF,TSS,SSA,SDN,SUR,SWE,CHE,SYR,TJK,TZA,THA,TLS,TGO,TON,TTO,TUN,TUR,TKM,TCA,TUV,UGA,UKR,ARE,GBR,USA,UMC,URY,UZB,VUT,VEN,VNM,VIR,WLD,YEM,ZMB,ZWE
Indicator Code,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5,EN.GHG.CO2.MT.CE.AR5
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1970,1.7328,228.5328,43.1109,4.8451,19.6910,0.0,8.9339,0.1027,277.7397,87.6199,10.0914,0.0254,160.6939,53.0045,24.1529,1.4413,3.2202,3.3393,0.3603,60.1650,139.5287,0.0599,0.4604,0.1388,0.0351,3.0253,11.2398,0.1536,107.1388,0.0073,2.0244,69.0654,0.2267,0.0583,0.1500,0.2134,1.1807,358.1619,11.0997,0.0258,0.0757,879.8067,0.1537,28.8614,911.5013,28.8484,0.0219,2.9277,1.8033,1.4344,2.6158,15.8791,21.8964,2.1681,188.2940,61.9641,0.7116,0.0076,3.8837,1181.6371,2233.6842,1049.3764,1123.3624,5.0207,25.4571,1.6023,0.0416,0.3417,21.3487,0.2570,1.1679,2590.7262,6524.7775,2784.5430,964.1768,3506.5941,0.0009,0.7117,41.5720,673.1504,469.2134,0.1414,0.6038,0.0793,23.9321,1084.1188,2.3446,0.0695,28.9447,0.0008,0.0114,0.0001,2.5031,0.4594,0.0442,1.5025,0.5336,42.2552,11854.4958,1.2210,9.5265,66.2777,4858.3491,5059.3291,122.6049,78.3751,200.9800,1.9334,212.7961,31.1237,80.4035,23.5611,20.6624,14.9146,314.6077,8.0512,848.7320,2.7408,184.9007,3.7483,0.0188,75.9808,62.3353,39.8386,15.4522,0.2914,3511.4861,550.1935,412.6958,497.3454,11.3365,47.3246,5.4315,0.0736,0.9716,40.0356,19.9282,3227.0245,101.2456,485.7807,19.6803,0.3034,0.7685,0.3457,27.4828,0.0099,0.2471,0.6831,0.0,0.3332,0.3065,120.8969,0.0001,388.9676,236.7855,236.7855,3125.7789,19.2867,5.5788,6.9356,3.1582,4.8125,0.7402,0.0,0.3337,134.1426,1.0776,15.4916,1.6554,0.2105,28.8483,4953.1067,9.2244,0.0,36.3784,10327.7438,7.3515,29.7817,2.9511,17.8574,1.9948,2.5998,1.1282,0.6340,17.4177,26.6109,309.1133,17.4870,10350.7720,95.8351,29.4485,14.7010,124.9786,1301.3298,0.0993,0.0658,0.0144,52.0083,1.3492,0.1069,0.3664,8.0008,43.8975,9.6877,43.8325,0.0659,0.5713,185.5633,219.6351,219.6351,142.8352,3.1210,0.0148,0.0301,0.0114,271.6437,271.6437,270.3689,3.4371,0.6270,96.1748,41.3531,6.3390,8.1401,1.5680,20.1643,0.0107,0.5454,0.0189,6.9307,4.2609,45.4589,18.7614,0.0033,0.0,0.9370,474.5121,19.4648,673.6238,4594.8060,2639.9982,5.4193,54.0140,0.0751,59.3201,17.5073,0.0001,15750.720652,1.6276,3.7004,9.5321
1971,1.7326,227.1802,57.2307,4.8382,23.0114,0.0,8.5196,0.1026,296.0924,87.9416,10.1074,0.0290,162.4245,55.6703,24.1757,1.4639,3.2389,3.3461,0.3595,60.2610,129.4105,0.0599,0.3625,0.1387,0.0371,3.7729,11.2766,0.1537,106.7785,0.0073,1.8711,69.0030,0.2269,0.0584,0.1500,0.2164,0.9288,365.8197,11.0631,0.0276,0.0757,891.2351,0.1539,31.3075,914.9404,29.1545,0.0219,2.9579,2.0656,1.4475,2.6676,16.1132,22.0739,2.1849,188.5532,57.6945,0.7116,0.0076,3.9319,1194.8028,2238.2132,1053.9632,1128.2928,4.4918,25.1650,1.6115,0.0416,0.3399,21.3740,0.2570,1.1716,2603.0654,6537.1372,2798.3161,967.5460,3518.5621,0.0009,0.7206,40.9850,677.4056,481.3232,0.1415,1.1169,0.0793,23.6550,1077.0031,2.3843,0.0695,29.9941,0.0008,0.0114,0.0002,2.5020,0.4622,0.0442,1.5025,0.5385,43.0575,11763.4106,1.2213,9.5651,67.9282,4878.7616,5094.2026,136.9077,78.5333,215.4410,2.0318,213.2897,31.4961,86.1897,27.5382,23.1425,14.9318,329.2742,8.0388,846.4325,2.7614,184.6426,3.7481,0.0188,76.3244,62.9871,42.2007,15.4730,0.2916,3544.1153,554.6220,413.7895,499.2660,11.3513,46.9026,5.5040,0.0737,0.9660,28.1244,19.9935,3251.0071,101.5075,501.2457,18.2823,0.3034,0.7696,0.3423,27.8776,0.0099,0.2458,0.6831,0.0,0.3347,0.3066,121.2965,0.0001,413.3463,238.0776,238.0776,3149.4996,19.3037,5.5779,6.9594,3.1705,4.8352,0.7406,0.0,0.3348,134.6596,1.0777,15.0987,1.6628,0.2067,42.6302,4825.6314,8.6594,0.0,35.1004,10214.4760,7.3520,29.7711,2.9600,18.0927,1.9948,2.6049,1.1283,0.6449,17.3804,26.8636,317.5662,18.6416,10219.1537,113.1783,31.7509,18.2966,125.7750,1302.3127,0.0994,0.0658,0.0144,63.1358,1.3488,0.1069,0.3665,8.0238,43.8575,9.7200,43.7942,0.0659,0.5713,184.4596,220.1688,220.1688,139.4015,3.1512,0.0148,0.0300,0.0114,284.4109,284.4109,283.1324,3.4481,0.6274,88.9766,43.3132,6.3711,8.1736,1.5684,20.2420,0.0108,0.3725,0.0189,6.8721,4.2753,49.7715,18.7824,0.0033,0.0,0.9437,474.1451,25.4298,668.8829,4459.6730,2648.2539,5.3985,54.2808,0.0751,57.9405,17.5233,0.0001,15682.550812,1.6408,3.8575,9.4795
1972,1.6924,236.1448,70.5594,5.5184,35.1514,0.0,10.3661,0.1249,329.6812,89.7663,10.8206,0.0396,168.2736,57.8830,25.7965,1.7257,3.8272,3.4703,0.4127,64.3722,141.0189,0.0726,0.4625,0.1690,0.0403,4.4981,11.0865,0.1972,116.2631,0.0089,2.2028,71.3147,0.2261,0.0582,0.1492,0.2326,0.9688,383.0701,11.1059,0.0358,0.0755,918.4919,0.1535,32.6492,975.4309,29.8753,0.0218,3.0425,1.9782,1.6223,2.9649,15.7912,21.6974,2.6640,188.4852,59.7421,0.7080,0.0092,5.0610,1283.8572,2355.4667,1109.7477,1187.0519,4.4818,27.3454,1.8549,0.0479,0.3217,23.2421,0.2634,1.0879,2723.0982,6803.6762,2947.4139,1027.8568,3664.0267,0.0010,0.7690,44.3527,710.0264,498.8697,0.1508,1.2037,0.0789,25.1287,1104.9335,2.4963,0.0596,36.8155,0.0008,0.0138,0.0002,2.7444,0.4647,0.0440,1.5246,0.5228,45.1011,12331.1455,1.2732,9.8510,70.0556,5144.4582,5379.8386,153.6041,81.7763,235.3804,2.2451,221.3891,37.2634,96.2358,27.3941,22.7710,15.7359,347.3733,8.0073,892.9819,2.3157,196.5706,3.9135,0.0201,79.2990,64.8740,42.4530,16.4308,0.3104,3733.4433,591.7243,440.1119,529.3456,12.0754,49.9877,6.0128,0.0734,0.9680,21.1840,21.3072,3447.1577,104.6039,535.6182,17.9121,0.3233,0.7884,0.3657,14.9216,0.0106,0.2482,0.8563,0.0,0.3369,0.3358,133.3843,0.0001,458.4677,257.5251,257.5251,3342.5538,20.4197,5.1301,7.7650,2.9157,4.7253,0.7328,0.0,0.4084,150.4304,1.1218,17.2591,1.7165,0.2267,55.2513,5093.7810,8.7359,0.0,38.0934,10692.3959,7.3593,32.8716,3.0248,18.8413,1.9948,2.8000,1.2031,0.7021,17.3957,27.8202,330.8947,19.0331,10690.4601,128.8462,38.8672,22.0216,131.2593,1370.2972,0.1056,0.0702,0.0143,80.9419,1.4312,0.1064,0.3647,9.3815,44.6031,9.4634,47.0023,0.0703,0.5684,191.0963,229.1021,229.1021,151.7023,3.7834,0.0180,0.0364,0.0138,306.7042,306.7042,305.5099,3.6481,0.7219,89.1769,44.0156,6.1415,8.5641,1.8343,22.6895,0.0115,0.4182,0.0202,6.4323,4.8126,57.6967,19.7400,0.0040,0.0,0.9278,499.6476,27.7474,657.9363,4710.5419,2806.9356,5.8160,57.3285,0.0801,59.5311,16.9843,0.0001,16478.735506,1.9251,4.2658,9.0937
1973,1.7325,257.7865,91.7658,4.9520,47.2995,0.0,11.3470,0.1260,380.4390,92.8514,11.7601,0.0445,177.6350,61.1926,27.9711,1.7181,4.7655,4.0992,0.4086,70.3457,146.4168,0.0733,0.4774,0.1705,0.0424,4.1882,12.0862,0.2625,135.2140,0.0090,2.6748,72.2951,0.2336,0.0600,0.1544,0.2835,1.0115,402.0165,11.6058,0.0383,0.0780,962.3009,0.1586,32.5657,1015.1823,30.8247,0.0225,3.0611,8.9589,1.8329,3.0499,17.3248,23.3866,2.7722,186.5306,58.7920,0.7327,0.0093,5.0553,1404.5056,2551.5836,1162.9893,1242.0267,5.6672,25.4613,2.0217,0.0289,0.3246,26.5529,0.2760,1.1881,2882.1532,7184.1954,3130.5107,1094.9249,3856.9309,0.0010,0.9152,48.4255,770.7974,535.5095,0.1814,3.8555,0.0817,26.6438,1157.3697,2.5508,0.0600,39.3849,0.0009,0.0139,0.0002,2.9141,0.4807,0.0455,1.7661,0.5501,54.5394,13031.4165,1.4011,9.9380,74.8751,5473.4322,5737.8464,178.4746,85.9396,264.4142,2.5818,220.0466,42.0333,114.7257,30.0637,22.3390,16.8465,369.5314,8.5489,1006.6046,2.6140,210.0251,4.0538,0.0241,81.0322,79.8860,38.0842,17.3029,0.3716,3955.8786,642.2880,478.1370,573.9818,13.0278,53.3844,7.4130,0.0759,0.9990,19.8506,22.8964,3684.1550,107.8258,568.8324,19.3450,0.3883,0.7295,0.3920,15.4101,0.0126,0.2590,0.8224,0.0,0.3492,0.3741,143.5069,0.0001,528.8621,292.1181,292.1181,3576.3292,21.7504,5.5144,9.1597,3.1029,3.7662,0.7580,0.0,0.5472,156.7448,1.3275,18.6515,1.9014,0.2666,66.4423,5298.8080,10.1017,0.0,38.6668,11268.9182,7.3929,37.1572,3.2237,20.0487,1.9948,3.1257,1.4471,0.7758,18.4316,31.5036,348.5825,21.1917,11268.4595,152.8192,43.1056,24.6715,143.4372,1453.9462,0.1088,0.0844,0.0148,108.3174,1.5399,0.1101,0.3772,10.2748,45.9857,10.7928,51.9867,0.0845,0.5881,208.2594,228.6942,228.6942,164.5273,3.9462,0.0181,0.0368,0.0140,349.5523,349.5523,348.2541,4.7929,0.7507,90.2652,47.6477,5.8373,8.9350,1.9050,25.3137,0.0135,0.3672,0.0242,6.6709,4.8371,62.4938,20.6212,0.0040,0.0,0.8552,529.2850,35.8436,690.2576,4896.6210,3007.4968,5.4934,60.6509,0.0964,67.2240,18.9263,0.0001,17461.301237,2.3423,4.5698,10.5544
1974,2.1886,264.9263,113.8977,5.3297,39.9008,0.0,11.8066,0.1123,372.5317,93.3312,12.6736,0.0436,187.1627,58.7040,30.1523,1.5017,5.5732,4.3162,0.3754,76.1497,145.2484,0.0654,0.4899,0.1519,0.0432,3.9877,13.0696,0.4534,146.0012,0.0080,2.7760,73.1629,0.2514,0.0642,0.1667,0.3215,0.9862,410.0923,11.1488,0.0362,0.0840,972.2772,0.1708,30.7345,1032.7302,31.9307,0.0243,3.2158,12.8843,1.7991,3.1332,18.6624,25.3653,2.1228,169.7728,52.3907,0.7913,0.0083,5.4048,1464.5423,2590.7685,1185.7374,1267.8771,6.9189,29.4337,2.0585,0.0352,0.3172,29.5769,0.2887,1.2027,2834.8854,7202.4266,3276.8634,1148.4454,3798.0090,0.0011,1.1070,44.6127,814.4281,516.7665,0.2225,3.9575,0.0882,27.9271,1122.1624,2.7186,0.0600,38.5970,0.0009,0.0124,0.0002,3.0229,0.5137,0.0491,1.5581,0.5992,58.8996,12840.0384,1.3743,11.3880,76.9219,5688.7885,5984.2233,205.2204,90.2144,295.4348,2.5270,235.8550,46.9566,121.7045,32.3560,24.1719,17.3021,372.0568,8.8517,1003.1685,2.8415,218.1677,4.0929,0.0296,84.1345,84.0060,31.1600,18.0726,0.4540,4087.7150,669.2920,510.7469,601.4595,13.9401,55.2918,7.5322,0.0818,1.0734,13.4682,24.4912,3845.9108,113.4002,614.6734,17.8088,0.4759,0.7202,0.4110,18.4524,0.0154,0.2735,0.7531,0.0,0.3742,0.4433,158.3182,0.0001,530.2081,297.2205,297.2205,3732.5106,22.9671,6.1328,10.1164,2.9303,4.3418,0.8151,0.0,0.4909,148.6930,1.6146,19.3606,2.0342,0.2495,84.0020,5137.7118,10.3919,0.0,37.0863,11021.5283,7.7617,39.6799,3.4868,21.2816,1.9948,3.1868,1.7757,0.7506,19.9895,29.9974,361.7476,21.2487,11021.1863,177.6089,40.8740,20.8140,145.6299,1529.2152,0.1089,0.1036,0.0160,113.6128,1.6497,0.1189,0.4065,10.7216,46.7351,11.6364,54.3155,0.1037,0.6346,215.0008,244.1185,244.1185,176.8972,3.3978,0.0162,0.0328,0.0125,378.8240,378.8240,377.5024,4.5204,0.6766,83.4978,42.9607,7.9431,9.3205,1.7474,25.2935,0.0163,0.3401,0.0297,6.7771,5.3315,65.0600,21.6244,0.0036,0.0,0.8938,553.2650,36.0107,644.8741,4727.4676,3117.8372,5.3208,64.2742,0.1183,66.1976,15.7784,0.0001,17397.837499,2.3311,4.6144,10.4036

In [33]:
df.head(2)

,Country Name,Country Code,Indicator Code,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,EN.GHG.CO2.MT.CE.AR5,0.0254,0.0290,0.0396,0.0445,0.0436,0.0576,0.0566,0.0673,0.0721,0.0761,0.0799,0.0831,0.0820,0.0846,0.0988,0.1043,0.1139,0.1289,0.1430,0.1976,0.2010,0.2264,0.2508,0.2516,0.2858,0.3144,0.2068,0.3430,0.3512,0.3559,0.2689,0.2719,0.2970,0.3424,0.3494,0.3853,0.4242,0.4581,0.4545,0.4933,0.4828,0.2907,0.3754,0.4128,0.4411,0.4625,0.4854,0.4671,0.4653,0.5095,0.4887,0.5074,0.5355,0.5371,0.5560
1,Africa Eastern and Southern,AFE,EN.GHG.CO2.MT.CE.AR5,228.5328,227.1802,236.1448,257.7865,264.9263,277.4182,289.9791,293.7755,273.4407,279.7941,296.4287,308.1463,311.9771,315.0471,333.2586,341.1111,341.8973,362.7894,368.8669,366.0531,378.5089,370.7246,364.3912,364.4796,372.7987,392.5591,407.2145,423.8012,431.6088,418.7455,425.0290,436.8347,450.4351,473.9017,510.4845,524.9596,534.2167,557.2612,588.3964,561.8464,576.4621,569.3149,589.1126,613.4711,635.8143,623.6060,628.1540,637.9923,646.7127,655.3423,613.7192,631.4195,618.5414,619.3657,634.4063